// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Z1qpd6ldcnRowY9W1JoYK0vQTSvKmdc',
    appId: '1:823032905127:web:4d26fcc9aca080d0e38a82',
    messagingSenderId: '823032905127',
    projectId: 'punsmart-119de',
    authDomain: 'punsmart-119de.firebaseapp.com',
    storageBucket: 'punsmart-119de.appspot.com',
    measurementId: 'G-3PT610GQZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNbVXIBe6pw3gtJD-86D1DDDEfOlud260',
    appId: '1:425054115382:android:5213f0193525e182ebea97',
    messagingSenderId: '425054115382',
    projectId: 'puntos-smart-650e5',
    storageBucket: 'puntos-smart-650e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk8bkWJyOKu-7UPQdZdWWxoLUilL8AD6I',
    appId: '1:425054115382:ios:e06f9f17ee70e039ebea97',
    messagingSenderId: '425054115382',
    projectId: 'puntos-smart-650e5',
    storageBucket: 'puntos-smart-650e5.appspot.com',
    androidClientId: '425054115382-2r8e4beooo33iq0nun9aelj9pgld6b4p.apps.googleusercontent.com',
    iosClientId: '425054115382-gh5pnno2d7mpmir9et7lamat2h31deq2.apps.googleusercontent.com',
    iosBundleId: 'com.puntossmart.puntossmart.v2',
  );

}